### ISSUE TITLE
data.zip can't be downloaded

### ISSUE THREAD

**Issue by dreamingtech** [PyUnit/pyunit-calendar#1]
BatchCalendar.load_date('temp') #下载数据
https://dev.tencent.com/u/zhangwei0530/p/logo/git/raw/master/date.zip

![image](https://user-images.githubusercontent.com/26395688/78770376-12d7c100-79c1-11ea-99ca-a784e5b6c409.png)

**Comment by jtyoui** [comment]
> BatchCalendar.load_date('temp') #下载数据
> https://dev.tencent.com/u/zhangwei0530/p/logo/git/raw/master/date.zip
> 
> ![image](https://user-images.githubusercontent.com/26395688/78770376-12d7c100-79c1-11ea-99ca-a784e5b6c409.png)

已经修复了,我已经讲数据直接放在库中,还增加了docker项目.
